### ISSUE TITLE
xmile v1.0

### ISSUE THREAD

**Issue by javimarlop** [jandraor/readsdr#1] opened 2020-11-17 16:48 UTC
Hi, I am trying to read a xmile file (using read_xmile) exported from the latest version of Vensim and it just says "Error: Invalid XML file". The header of the .xmile model file is as follows:

```
<?xml version="1.0" encoding="utf-8" ?>
<xmile version="1.0" xmlns="http://docs.oasis-open.org/xmile/ns/XMILE/v1.0">
	<header>
		<product version="1.0" lang="en">Vensim</product>
		<vendor>Ventana Systems, Inc.</vendor>
		<created>
		</created>
		<modified>
		</modified>
		<name>
		</name>
		<caption>
		</caption>
	</header>
	<sim_specs method="RK4" time_units="Year">
		<start>1961</start>
		<stop>2070</stop>
		<dt>1</dt>
	</sim_specs>
	<model>
```

Any idea what could be the problem?

Thanks!

**Comment by jandraor** [comment] 2020-11-17 20:29
Hi Javier,

I would need a minimal reproducible example.  The XML code you posted is incomplete as there are open tags (e.g., there is no closing tag for "model"), so I can't say what the problem is. "Invalid XML file" means that there is a problem with the XML code's structure. Probably, there is an invalid character or something similar. Vensim doesn't escape special characters. I really can't tell. If you can build something simple and complete that represents your model,  it would be of great help.

**Comment by javimarlop** [comment] 2020-11-18 09:47
Hi! Thanks. It is a large model but I tried read_xml and it gives an error: "StartTag: invalid element name [68]". Not sure if this refers to line number but there is no strange character there, unless question marks, colon, etc. are an issue. I guess the problem should be within the notes of the variables but I am not sure if there is a way to ignore them. The encoding of the file is utf-8. I will keep trying!

**Comment by javimarlop** [comment] 2020-11-18 10:30
ok, I now checked the code using https://www.w3schools.com/xml/xml_validator.asp and found out that errors occur when using "<=" in IF ELSE conditions, as they seem to be confused with invalid StartTags. Could this be possible? Thanks!

**Comment by jandraor** [comment] 2020-11-18 11:15
Since Vensim doesn't escape symbols, when reading "<", the XML parser interprets it as a tag opening. There is a function in the package that tries to fix those errors but apparently it is not 100 % working. Could you send me the complete tag of that variable?

<aux name =.....>
.
.
.
</aux>

**Comment by javimarlop** [comment] 2020-11-18 11:21
`			<aux name="tourist_growth">
				<units>percentage</units>
				<doc></doc>
					<eqn>IF_THEN_ELSE(expected_number_of_tourists_per_season<=maxPotTourists, (Initial_nr_of_tourists+expected_number_of_tourists_per_season)*(growth_rate_of_tourism
	+incentives_on_tourism_development), 0)					</eqn>
			</aux>`

**Comment by jandraor** [comment] 2020-11-18 11:35
I tried that code and it worked properly. I don't know what the problem is.

**Comment by javimarlop** [comment] 2020-11-18 11:38
ok, I thought that was the problem but I will keep trying. Thanks!

**Comment by jandraor** [comment] 2020-11-18 11:47
I guess the sanitising function is not translating all unescaped symbols. I would have to look at the whole file. But I presume that is not possible for confidentiality issues. As a workaround,  you could manually change in the XMILE file all the "<" and ">" for their escape versions. Thus, if you have `a < b`, you will change it to `a &lt b`. 

Also, the sanitising function only escapes 'greater than' and 'less than'. It doesn't escape single quotes, double quotes, and ampersand.

**Comment by javimarlop** [comment] 2020-11-18 11:55
ok, thanks! I will try changing it manually. I have several <= as well which I can try to convert as well. I could send you the file privately via e-mail if you send me your address.

**Comment by jandraor** [comment] 2020-11-18 11:57
jair.andrade@nuigalway.ie

Thanks.

**Comment by jandraor** [comment] 2020-11-18 12:51
Variable documentation should not contain unescaped forbidden characters (<, >, &, ', ").

**Closed by jandraor** 2020-11-18 12:51 UTC
